UMAR proxy is set!
Attaching package: 'dplyr'

The following objects are masked from 'package:stats':

    filter, lag

The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union

Error in `map()`:
i In index: 1.
Caused by error in `insert_new_data()`:
! could not find function "insert_new_data"
Backtrace:
     x
  1. +-base::source("\\\\192.168.38.7\\public$\\Avtomatizacija\\umar-automation-scripts\\R\\surs-update-database.R")
  2. | +-base::withVisible(eval(ei, envir))
  3. | \-base::eval(ei, envir)
  4. |   \-base::eval(ei, envir)
  5. +-base::system.time(purrr::walk(df$code, ~insert_new_data(.x, con)))
  6. +-purrr::walk(df$code, ~insert_new_data(.x, con))
  7. | \-purrr::map(.x, .f, ..., .progress = .progress)
  8. |   \-purrr:::map_("list", .x, .f, ..., .progress = .progress)
  9. |     +-purrr:::with_indexed_errors(...)
 10. |     | \-base::withCallingHandlers(...)
 11. |     +-purrr:::call_with_cleanup(...)
 12. |     \-global .f(.x[[i]], ...)
 13. \-base::.handleSimpleError(...)
 14.   \-purrr (local) h(simpleError(msg, call))
 15.     \-cli::cli_abort(...)
 16.       \-rlang::abort(...)
Timing stopped at: 0.18 0.01 0.31
Execution halted
